mutation($links: [NavigationHeaderLinkInput]!) {
  navigation {
    updateHeaderLinks(links: $links) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
